const sessionId = "5b1c6f3e-2a4d-4e8f-9b0a-1c2d3e4f5a6b";
const bankId = "6f1c2c1e-8a8f-4b5e-9a65-1d7c5b0f2a10";
const change = { kind: "draft", name: "fact", path: "projects/personal/homelab/memories/fact.md", content: "A fact." };
const repositoryIdentity = "https://git.example.test/maya/homelab";
const input = { scope: { org: "personal", project: "homelab" }, name: "fact", description: "When reading the homelab facts, follow these verified steps and measurements.", body: "A fact.", type: "project" };
export const memoryDraftSchemaFixtures = {
  "sessions/events/session.bank-used.json": { valid: [{ bankId, pointers: ["maya-memory:personal/homelab/"] }], invalid: [{ bankId, pointers: [] }, { bankId, pointers: ["/etc/passwd"] }] },
  "banks/scope-segment.json": { valid: ["personal"], invalid: ["../secret", ""] },
  "banks/draft-scope.json": { valid: [input.scope, { ...input.scope, area: "deploy" }], invalid: [{ org: "personal" }, { ...input.scope, area: "../secret" }] },
  "banks/tools/search.json": { valid: [{ query: "backup" }, { query: "backup", bank: "maya-memory", scope: { org: "personal" }, limit: 10 }, { query: "backup", scope: input.scope }], invalid: [{ query: "" }, { query: "fact", bank: "../secret" }, { query: "fact", scope: { org: "personal", area: "nas" } }] },
  "banks/tools/read.json": { valid: [{}, { pointer: "maya-memory:personal/homelab/" }, { pointer: "maya-memory:fact" }], invalid: [{ pointer: "" }, { pointer: 1 }] },
  "banks/tools/promote.json": { valid: [{}, { bank: "maya-memory" }], invalid: [{ bank: "../secret" }, { bank: 2 }] },
  "banks/promote-result.json": { valid: [{ state: "landed", bank: "maya-memory", pullRequest: null, files: [{ path: change.path, state: "present" }] }, { state: "awaiting-review", bank: "maya-memory", pullRequest: "https://git.example.test/maya/memory/pulls/1", files: [{ path: change.path, state: "pending" }] }, { state: "failed", bank: "maya-memory", step: "validate-check", reason: "Failed." }], invalid: [{ state: "landed", bank: "maya-memory", pullRequest: null, files: [{ path: change.path, state: "pending" }] }, { state: "failed", bank: "maya-memory" }] },
  "banks/events/bank.drafts-consumed.json": { valid: [{ sessionId, bankId, changes: [change] }], invalid: [{ bankId, changes: [] }, { sessionId, bankId, changes: [{}] }] },
  "banks/tools/draft.json": { valid: [input, { ...input, bank: "maya-memory", topic: "deploy", appliesTo: ["https://git.example.test/maya/homelab"] }], invalid: [{ ...input, type: "status" }, { ...input, scope: {} }] },
  "banks/tools/retire.json": { valid: [{ bank: "maya-memory", name: "fact", reason: "Replaced." }], invalid: [{ name: "fact", reason: "Replaced." }, { bank: "maya-memory", name: "fact", reason: "" }] },
  "banks/draft.json": { valid: [change, { kind: "retire", name: "fact", path: change.path, reason: "Replaced." }], invalid: [{ ...change, kind: "promote" }, { ...change, content: 1 }] },
  "banks/events/bank.draft-queued.json": { valid: [{ sessionId, bankId, change }], invalid: [{ bankId, change }, { sessionId, bankId: "bank", change }] },
};
export const memoryDraftMethodFixtures = {
  "banks.drafts.list": { params: { valid: [{ sessionId }, { sessionId, bankId }], invalid: [{}, { sessionId: "session" }] }, result: { valid: [{ queues: [] }, { queues: [{ bankId, drafts: [change] }] }], invalid: [{ drafts: [] }, { queues: [{ bankId, drafts: [{ kind: "promote" }] }] }] } },
  "banks.memory.search": { params: { valid: [{ query: "backup", repositoryIdentity: null }, { query: "backup", bank: "maya-memory", scope: input.scope, limit: 10, repositoryIdentity }], invalid: [{ query: "backup" }, { query: "", repositoryIdentity: null }, { query: "backup", repositoryIdentity: "/home/maya/homelab" }] }, result: { valid: [{ text: "maya-memory:fact A fact.\n1 of 1" }], invalid: [{}, { text: 1 }] } },
  "banks.memory.read": { params: { valid: [{ repositoryIdentity: null }, { pointer: "maya-memory:personal/homelab/", repositoryIdentity }], invalid: [{}, { pointer: "", repositoryIdentity: null }] }, result: { valid: [{ text: "A fact." }], invalid: [{}, { text: null }] } },
  "banks.memory.draft": { params: { valid: [{ ...input, queue: sessionId, repositoryIdentity: null }, { ...input, bank: "maya-memory", topic: "deploy", queue: sessionId, repositoryIdentity }], invalid: [{ ...input, repositoryIdentity: null }, { ...input, queue: "session", repositoryIdentity: null }, { ...input, type: "status", queue: sessionId, repositoryIdentity: null }] }, result: { valid: [{ bank: "maya-memory", change }], invalid: [{ change }, { bank: "maya-memory", change: { ...change, kind: "promote" } }] } },
  "banks.memory.promote": { params: { valid: [{ queue: sessionId, repositoryIdentity: null }, { bank: "maya-memory", queue: sessionId, repositoryIdentity }], invalid: [{ repositoryIdentity: null }, { queue: sessionId }, { bank: "../secret", queue: sessionId, repositoryIdentity: null }] }, result: { valid: [{ promotion: { state: "landed", bank: "maya-memory", pullRequest: null, files: [] } }, { promotion: { state: "failed", bank: "maya-memory", step: "fetch", reason: "Failed." } }], invalid: [{}, { promotion: { state: "failed", bank: "maya-memory" } }] } },
};
